[package]
name = "rust_to_do_list"
version = "1.0.0"
authors = ["Ruby-Dragon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
ansi_term = "0.12"
dirs = "4.0"
